package com.freeman_smith.tthfunfacts;

import java.util.Random;

/**
 * Created by Karen Freeman-Smith on 11/12/2016.
 */

public class FactBook {
    protected String[] mFacts = {
            "If food is not mixed with saliva, you can't taste it.",
            "Lemons contain more sugar than strawberries.",
            "Reindeer like bananas.",
            "Cats spend 66% of their life asleep.",
            "Honey is the only natural food that never spoils.",
            "The only continent with no active volcanos is Austalia.",
            "Coca-Cola originally contained cocaine.",
            "Toilets account for 35% of indoor water use.",
            "Fortune cookies were invented in San Francisco",
            "You can buy beer brewed from bananas (in eastern Africa).",
            "An average human brain is 78% water.",
            "Frogs can't swallow with their eyes open.",
            "A one-minute kiss burns 26 calories.",
            "You burn more calories sleeping than watching TV.",
            "Hummingbirds can fly backwards.",
            "Popcorn was invented by the Aztecs.",
            "The average person will spend 25 years of their life asleep.",
            "French fries are originally from Belgium.",
            "Cows don't have upper front teeth.",
            "The safest car color is white.",
            "Apples wake you up better than coffee.",
            "An octopus pupil is rectangular.",
            "The oldest word in the English language is 'town'.",
            "Venetian blinds were invented in Japan.",
            "'Strengths' is the longest word in the English language with just one vowel.",
            "The Amazon rain forest produces half the world's oxygen supply.",
            "A group of frogs is called an army.",
            "A group of kangaroos is called a mob.",
            "Brazil was named after a tree.",
            "Cat urine glows under a blacklight.",
            "The wheelbarrow was invented in China.",
            "Pearls melt in vinegar.",
            "Giraffes can last longer than camels without water.",
            "The electric chair was invented by a dentist.",
            "Rubber bands last longer when refrigerated.",
            "Women blink twice as often as men.",
            "An egg has every vitamin except C.",
            "Your foot and forearm are the same length.",
            "Ants stretch when they wake up in the morning.",
            "A piece of paper cannot be folded more than 7 times.",
            "The electric toothbrush was invented in 1939.",
            "Hawaii is the only US state that grows coffee.",
            "Einstein slept 10 hours a night.",
            "Peru has more pyramids than Egypt.",
            "More people die from falling coconuts than shark attacks.",
            "Over 2,500 left-handed people die each year from using right-handed products.",
            "The oldest known vegetable is the pea.",
            "The most fatal car accidents happen on Saturdays.",
            "Human thigh bones are stronger than concrete.",
            "More people are killed by bees than by snakes.",
            "Men are struck by lightning 7 times more often than women.",
            "Your most active muscles are in your eye.",
            "13 people a year are killed by vending machines.",
            "Rain contains vitamin B12.",
            "Your brain uses 25% of the oxygen you breathe.",
            "A full moon is 9 times brighter than a half-moon.",
            "Flies always launch backwards.",
            "A snail can sleep for 3 years.",
            "Tarantulas can survive 2.5 years without food.",
            "Crocodiles swallow rocks to help them dive deeper.",
            "Grasshoppers have white blood.",
            "It takes 2 hours to boil an Ostrich egg.",
            "There are no rivers in Saudi Arabia.",
            "Dirty snow melts quicker than clean snow.",
            "The first printed book in England was about chess.",
            "The most frequently sung song is 'Happy Birthday'.",
            "The yo-yo was originally used for hunting in the Philippines.",
            "Blond beards grow faster than dark beards.",
            "The hydrochloric acid in your stomach is strong enough to dissolve a nail.",
            "Humans have fewer muscles than caterpillars.",
            "You shed a complete layer of skin every 4 weeks.",
            "The Chinese have been using fingerprints for identification for over 1300 years.",
            "Dolphins can hear sound underwater from 15 miles away.",
            "Turnips turn green when they get sunburned.",
            "Flamingos can only eat when their heads are upside down.",
            "Moisture, not air, causes super-glue to dry.",
            "A deck of playing cards should be shuffled at least 7 times before playing.",
            "Pinocchio is Italian for 'pine head'.",
            "The side of a hammer is called a cheek.",
            "People who work at night tend to weigh more.",
            "Most of the Vitamin C in fruits is found in the skin.",
            "You can buy square watermelons in Japan.",
            "Wearing headphones for an hour will increase the bacteria in your ear by 700 percent.",
            "There are a million ants for every person on earth.",
            "You use 72 different muscles while speaking.",
            "Coconuts kill over 150 people every year.",
            "It took Leonardo Da Vinci 10 years to pain the Mona Lisa.",
            "The most common disease is tooth decay.",
            "The average person goes to the bathroom 6 times a day.",
            "Giraffes have the highest blood pressure of any animal.",
            "Japan is the largest exporter of frogs legs.",
            "The longest time a person has spent in a coma was 37 years.",
            "You're more likely to get stung by a bee on a windy day.",
            "A rat can tread water for 3 days.",
            "Women invented bullet proof vests, fire escapes, laser printers, and windshield wipers.",
            "A shark can sense a drop of blood from 2.5 miles away.",
            "You can tell the sex of a horse by it's teeth.",
            "Cows produce more milk when they listen to music.",
            "Snakes can't bite in rivers or swamps.",
            "Shrimp are all born male and grow into females.",
            "Croissants were invented in Austria."};
    public String getFact() {


        String fact = "";
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mFacts.length);
        fact = mFacts[randomNumber];

        return fact;
    }
}
